-- CreateTable
CREATE TABLE "Project" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "name" TEXT NOT NULL,
    "technology" TEXT NOT NULL,
    "country" TEXT NOT NULL,
    "capacityMw" REAL NOT NULL,
    "status" TEXT NOT NULL,
    "ao" TEXT NOT NULL DEFAULT 'Non renseigne',
    "priority" TEXT NOT NULL DEFAULT 'Medium',
    "caseType" TEXT NOT NULL DEFAULT 'Base',
    "region" TEXT NOT NULL DEFAULT 'Non renseignee',
    "tariff" REAL NOT NULL DEFAULT 0,
    "commissioningYear" INTEGER NOT NULL DEFAULT 0,
    "debtSizingCentralW" REAL,
    "debtSizingLowW" REAL,
    "investorCurveW" REAL,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" DATETIME NOT NULL
);

-- CreateTable
CREATE TABLE "AuroraCurve" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "year" INTEGER NOT NULL,
    "high" REAL NOT NULL,
    "central" REAL NOT NULL,
    "low" REAL NOT NULL,
    "technology" TEXT NOT NULL,
    "updatedAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- CreateTable
CREATE TABLE "Scenario" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "name" TEXT NOT NULL,
    "capex" REAL NOT NULL,
    "surfaceHa" REAL,
    "prixModuleUSDWc" REAL,
    "tauxEURUSD" REAL,
    "boSCtWc" REAL,
    "raccordementOuvrageK€" REAL,
    "tarifQPk€PerMW" REAL,
    "apportAffaireMode" TEXT,
    "apportAffaireValeur" REAL,
    "opex" REAL NOT NULL,
    "yieldMwh" REAL NOT NULL,
    "yieldP90Mwh" REAL,
    "tariff" REAL NOT NULL,
    "debtRate" REAL NOT NULL,
    "projectLifeYears" INTEGER NOT NULL DEFAULT 30,
    "degradationRate" REAL NOT NULL DEFAULT 0.3,
    "discountRate" REAL NOT NULL DEFAULT 6,
    "debtInterestRate" REAL NOT NULL DEFAULT 4,
    "debtMaturityYears" INTEGER NOT NULL DEFAULT 20,
    "tariffInflationRate" REAL NOT NULL DEFAULT 0,
    "opexInflationRate" REAL NOT NULL DEFAULT 2,
    "contractDuration" INTEGER,
    "constructionYears" INTEGER,
    "assuranceRate" REAL,
    "inflationAssurance" REAL,
    "balancingCost" REAL,
    "omFixedEuroKwc" REAL,
    "mraEuroKwc" REAL,
    "backOfficeKeuro" REAL,
    "diversOpexKeuro" REAL,
    "loyerMode" TEXT,
    "loyerValeur" REAL,
    "loyerInflation" REAL,
    "inflationOM" REAL,
    "inflationMRA" REAL,
    "inflationBackOffice" REAL,
    "inflationDivers" REAL,
    "methodeTaxes" TEXT,
    "tauxTFCommune" REAL,
    "tauxTFEPCI" REAL,
    "tauxTSE" REAL,
    "tauxGEMAPI" REAL,
    "tauxTEOM" REAL,
    "tauxCFECommune" REAL,
    "tauxCFEEPCI" REAL,
    "tauxCCI" REAL,
    "prixTerrainHa" REAL,
    "abattTerrain" REAL,
    "inflationTaxes" REAL,
    "iferRate1" REAL,
    "iferRate2" REAL,
    "iferRpn" REAL,
    "inflationAurora" REAL,
    "dscrTarget" REAL,
    "debtTenorYears" INTEGER,
    "dscrSchedule" TEXT,
    "gearingMax" REAL,
    "structuringFeeRate" REAL,
    "tauxIS" REAL,
    "amortDuree" INTEGER,
    "ccaApportKeuro" REAL,
    "ccaRemunRate" REAL,
    "dsraMonths" INTEGER,
    "ccaBloque" BOOLEAN,
    "devFeesKEuroPerMW" REAL,
    "tauxISEntreprise" REAL,
    "contingencyRate" REAL,
    "longueurModule" REAL,
    "largeurModule" REAL,
    "txAmenagementRate" REAL,
    "coefArcheo" REAL,
    "legalFeesK€" REAL,
    "technicalDDK€" REAL,
    "arrangerFeesRate" REAL,
    "participantFeesRate" REAL,
    "bankFeesPLTK€PerMW" REAL,
    "interimFinancingRate" REAL,
    "commitmentFeesRate" REAL,
    "unavailability" REAL,
    "indemnitesImmoKeuro" REAL,
    "aleasOpexRate" REAL,
    "tauxTSECfe" REAL,
    "tauxGEMAPICfe" REAL,
    "coefDegressif" REAL,
    "taxeFinaleSizingKeuro" REAL,
    "agentFeeAnnuelKeuro" REAL,
    "dsrfFeeRate" REAL,
    "capacityCertificateMw" REAL,
    "goStartYear" INTEGER,
    "goPriceBase" REAL,
    "curveIndexAn1" REAL,
    "fonciereBienEuroWc" REAL,
    "batimentsFonciersKeuro" REAL,
    "modRetraitementKeuro" REAL,
    "valeurTerrainKeuro" REAL,
    "opexEngagementsKeuroByYear" TEXT,
    "margeFactFigeeKeuro" REAL,
    "dscr" REAL NOT NULL,
    "npv" REAL NOT NULL,
    "irr" REAL NOT NULL,
    "lcoe" REAL NOT NULL,
    "isReference" BOOLEAN NOT NULL DEFAULT false,
    "projectId" TEXT NOT NULL,
    CONSTRAINT "Scenario_projectId_fkey" FOREIGN KEY ("projectId") REFERENCES "Project" ("id") ON DELETE CASCADE ON UPDATE CASCADE
);

-- CreateIndex
CREATE UNIQUE INDEX "AuroraCurve_year_key" ON "AuroraCurve"("year");

